#Page list of category
store_backend_category_list:
   path:     /list
   defaults: {_controller: 'StoreBackendBundle:Category:list'}

#Page view for category
store_backend_category_view:
   path:     /view/{id}/{name}
   requirements:
     id: \d+
     name: (.){1,100}
     _method: GET
   defaults: {_controller: 'StoreBackendBundle:Category:view'}

#Page delete category
store_backend_category_delete:
    path:        /delete/{id}
    requirements:
        id:      \d+
        _method: GET
    defaults:    {_controller: 'StoreBackendBundle:Category:delete'}

#Page new category
store_backend_category_new:
    path:        /new
    requirements:
        _method: GET|POST
    defaults:    {_controller: 'StoreBackendBundle:Category:new'}

#Route activate category
store_backend_category_activate:
    path: /activate/{id}/{active}
    requirements:
        id: \d+
        active: \d{1}
    defaults: {_controller: 'StoreBackendBundle:Category:activate'}