#Page list of cms
store_backend_cms_list:
   path:     /list
   defaults: {_controller: 'StoreBackendBundle:CMS:list'}

#Page view for cms
store_backend_cms_view:
   path:     /view/{id}/{name}
   requirements:
     id: \d+
     name: (.){1,50}
     _method: GET
   defaults: {_controller: 'StoreBackendBundle:CMS:view'}

#Page delete cms
store_backend_cms_delete:
    path:        /delete/{id}
    requirements:
        id:      \d+
        _method: GET
    defaults:    {_controller: 'StoreBackendBundle:CMS:delete'}